[build]
command = "ng build --configuration production"
publish = "dist/hopink-studio"

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/imagenes/*"
  to = "/imagenes/:splat"
  status = 200

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

[[redirects]]
  from = "/manifest.webmanifest"
  to = "/manifest.webmanifest"
  status = 200

[[redirects]]
  from = "/ngsw-worker.js"
  to = "/ngsw-worker.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
